### ISSUE TITLE
RFC: Refactoring DCS Dropzone Registry Using Markdown Files

### ISSUE THREAD

**Issue by JonathanTurnock** [flying-dice/dcs-dropzone-mod-manager#2]
### Background
DCS Dropzone currently uses a YAML file for its main index and the GitHub API for internal details. This system, while functional, has limitations in terms of flexibility and ease of content management.

### Objective
The objective of this RFC is to propose a refactoring of the registry system. The new system will utilize Markdown (`.md`) files with YAML front matter for storing mod properties and release information.

### New File Structure
1. **`index.md`**: 
   - Purpose: To serve as the main landing page for each mod, containing key properties.
   - Contents: Front matter for defining mod properties and Markdown content for descriptive information.

2. **`releases/latest.md`**: 
   - Purpose: To detail the latest release properties and additional content.
   - Contents: Front matter for release-specific properties and Markdown content for release notes or additional details.

### Front Matter Specification
- The front matter in both `index.md` and `releases/latest.md` will use YAML syntax.
- It will include necessary metadata for mods and releases, respectively.

### Example `index.md`
```yaml
---yml
name: Example Mod
authors: Mod Author
description: A brief description of the mod.
category: example
tags: [tag1, tag2]
---
Additional descriptive content about the mod.
```

### Example `releases/latest.md`
```yaml
---yml
version: 1.0.0
title: Example Name
date: 2024-01-01
---
Extended release notes or additional information.
```

## 3. Advantages

- **Flexibility**: Markdown files are easier to edit and manage, especially for non-technical contributors.
- **Clarity**: Separating mod properties and release details enhances clarity and organization.
- **Version Control**: Markdown files work well with version control systems like Git, making it easier to track changes.
