### ISSUE TITLE
RFC: Enhancement of DCS Dropzone Mod Manager with `install.md` File Integration

### ISSUE THREAD

**Issue by JonathanTurnock** [flying-dice/dcs-dropzone-mod-manager#6]
### Background
DCS Dropzone has evolved to use Markdown files with YAML front matter for mod properties and release information. This approach has significantly improved flexibility and clarity. However, there's still potential for further enhancement, particularly in the installation process of mods.

### Objective
This RFC proposes the integration of an `install.md` file into the DCS Dropzone Mod Manager. The `install.md` file will contain instructions for creating symlinks to target directories, enhancing the mod installation process. Additionally, it will handle hash-routed files, streamlining the process of sourcing mod files from external URLs.

### New File: `install.md`
- **Purpose:** `install.md` will serve as an instruction set for creating symlinks from the mod package to the target directories in the user's file system.
- **Contents:** It will contain YAML front matter for listing files/folders and their target directories. Additionally, it will support hash-routed URLs for sourcing files.

### Structure of `install.md`
- The file will list each file/folder in the mod package that needs to be symlinked.
- For each item, the source URL (possibly hash-routed) and the target directory on the filesystem will be specified.

### Example `install.md`
```yaml
---
- source: "http://xyz.com/simple-script.lua"
  target: "/path/to/target/directory/simple-script.lua"

- source: "http://xyz.com/my-mod.zip/#/my-folder/script.lua"
  target: "/path/to/target/directory/script.lua"

- source: "http://xyz.com/my-mod.zip/#/my-folder/texture.png"
  target: "/path/to/target/directory/texture.png"

- source: "http://xyz.com/my-mod.zip/#/my-folder"
  target: "/path/to/target/directory"
---
Instructions or additional notes about the installation process.
```

### Handling Hash-Routed Files
- The `install.md` file will support hash-routed URLs, enabling the sourcing of specific files within a ZIP file hosted externally.

## 3. Advantages

- **Efficient Installation Process: ** Automating the creation of symlinks through `install.md` simplifies the mod installation process and allows the mod author to have complete control of exactly whats linked.
- **Explicit Downloading:** Hash-routed URLs offer a way to fetch the assets and unpack them, but the hash routing allows the enable/disable process to work independently.
- **Clear Instructions:** `install.md` provides clear, structured instructions, beneficial for both mod creators and users.
- **Compatibility:** This system maintains compatibility with existing YAML and Markdown-based structures in DCS Dropzone.

## 4. Implementation Considerations

- **Security:** Ensure secure handling of external URLs and file operations to prevent vulnerabilities.
- **Documentation:** Provide clear documentation for mod creators on how to use `install.md`.

The general workflow of the Mod Manager would be

A) Subscribe to a mod
- DCS Dropzone calculates the Asset URLs (Grab everything before # and dedupe)
- DCS Dropzone downloads all assets into a mod folder.
- DCS Dropzone unpacks any assets that are needed i.e. ZIPs

B) Enable a mod
- DCS Dropzone calculates FS paths for the assets based on deterministic behaviour (i.e. converts http://xyz.com/simple-script.lua to $MOD_ID/simple-script.lua and http://xyz.com/my-mod.zip/#/my-folder/texture.png to $MOD_ID/my-mod_zip/my-folder/texture.png
- DCS Dropzone creates symlinks between folders & files (as determined above) and their targets
- DCS Dropzone records the symlinks for reference later when removing.

C) Disable a mod
- DCS Dropzone removes all symlinks as stored earlier.

D) Unsubscribe to a mod
- DCS Dropzone disables if enabled
- DCS Dropzone deletes mod folder
